/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// =================================================================================================
// IMPORTANT: ACTION REQUIRED
// =================================================================================================
// The values below are placeholders. You must replace them with the actual configuration values
// from your AWS Amplify project.
//
// To get these values:
// 1. Go to your AWS Amplify Console: https://console.aws.amazon.com/amplify/
// 2. Select your application.
// 3. In the backend environments tab, select your environment (e.g., 'staging' or 'prod').
// 4. At the top right, click the "View app details" button.
// 5. You will find the necessary IDs and keys here.
//
// Alternatively, if you have the Amplify CLI installed and configured, you can run:
// `amplify pull --appId <YOUR_APP_ID> --envName <YOUR_ENV_NAME>`
// This command will automatically generate and populate this file for you.
// =================================================================================================
// prettier-ignore
const awsmobile = {
    "aws_project_region": "ap-southeast-1", // <-- Replace with your project's region, e.g., "us-east-1"
    "aws_appsync_graphqlEndpoint": "https://<YOUR_APPSYNC_ENDPOINT>/graphql", // <-- Replace with your AppSync endpoint URL
    "aws_appsync_region": "ap-southeast-1", // <-- Replace with your AppSync region
    "aws_appsync_authenticationType": "API_KEY", // <-- Replace with your AppSync auth type (e.g., API_KEY, AMAZON_COGNITO_USER_POOLS)
    "aws_appsync_apiKey": "da2-<YOUR_API_KEY>", // <-- Replace with your AppSync API key
    "aws_cognito_identity_pool_id": "ap-southeast-1:xxxx-xxxx-xxxx-xxxx", // <-- Replace with your Cognito Identity Pool ID
    "aws_cognito_region": "ap-southeast-1", // <-- Replace with your Cognito region
    "aws_user_pools_id": "ap-southeast-1_xxxx", // <-- Replace with your Cognito User Pool ID
    "aws_user_pools_web_client_id": "xxxx", // <-- Replace with your Cognito Web Client ID
    "aws_user_storage_s3_bucket": "your-s3-bucket-name-for-storage-xxxx", // <-- Replace with your S3 bucket for user storage
    "aws_user_storage_s3_region": "ap-southeast-1" // <-- Replace with your S3 bucket region
};


export default awsmobile;