/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// =================================================================================================
// IMPORTANT: ACTION REQUIRED - THIS IS A CRITICAL CONFIGURATION FILE
// =================================================================================================
// The values below are placeholders. You MUST replace them with your actual configuration values
// from your AWS Amplify project for the app to function correctly. Leaving them as placeholders
// WILL CAUSE THE APP TO FAIL.
//
// To get your configuration values:
// 1. Go to your AWS Amplify Console: https://console.aws.amazon.com/amplify/
// 2. Select your application backend.
// 3. In the "Backend environments" tab, select your environment (e.g., 'staging' or 'prod').
// 4. Click the "View app details" button at the top right.
// 5. A modal will appear with your project details. Copy the values and paste them below.
//
// Alternatively, if you have the Amplify CLI installed and configured, you can run:
// `amplify pull --appId <YOUR_APP_ID> --envName <YOUR_ENV_NAME>`
// This command will automatically generate and populate this file for you.
// =================================================================================================
const awsmobile = {
    "aws_project_region": "ap-southeast-1", // <-- Replace with your project's region, e.g., "us-east-1"
    "aws_appsync_graphqlEndpoint": "https://<YOUR_APPSYNC_ENDPOINT>/graphql", // <-- Replace with your AppSync endpoint URL
    "aws_appsync_region": "ap-southeast-1", // <-- Replace with your AppSync region
    "aws_appsync_authenticationType": "API_KEY", // <-- Replace with your AppSync auth type (e.g., API_KEY, AMAZON_COGNITO_USER_POOLS)
    "aws_appsync_apiKey": "da2-<YOUR_API_KEY>", // <-- Replace with your AppSync API key
    "aws_user_storage_s3_bucket": "your-s3-bucket-name-for-storage-xxxx", // <-- Replace with your S3 bucket for user storage
    "aws_user_storage_s3_region": "ap-southeast-1" // <-- Replace with your S3 bucket region
};


export default awsmobile;